# Generated by Django 3.1.3 on 2020-11-23 13:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system_api', '0002_user_allow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allow_fields',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Email'), (1, 'Username'), (2, 'FirstName'), (3, 'LastName'), (4, 'Phone'), (5, 'Skype')], max_length=11),
        ),
    ]
