# Generated by Django 3.1.3 on 2020-12-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system_api', '0003_auto_20201123_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allow_fields',
        ),
    ]
