# Generated by Django 3.1.3 on 2020-11-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='access_token'),
        ),
    ]
