# Generated by Django 3.1.3 on 2020-12-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id_for_data_service',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
