# Generated by Django 3.1.3 on 2020-11-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201125_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='refresh_token'),
        ),
    ]
