# Generated by Django 3.1.3 on 2020-11-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201125_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='access_token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='refresh_token'),
        ),
    ]
