# Generated by Django 3.1.3 on 2020-12-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_myapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myapplication',
            old_name='allow_fields',
            new_name='scope',
        ),
    ]
